name: Build and publish electron app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_for_windows_xp:
    name: Build for Windows x86
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install -g @quasar/cli yarn --force
          rm package.json, yarn.lock, quasar.config.js
          ren package.x86.json package.json
          ren quasar.config.x86.js quasar.conf.js
          yarn install
      - name: Build and release Windows x86 binaries 
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T win32 --icon=/src-electron/icons/icon.ico
