name: Build and publish electron app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_for_windows_xp:
    name: Build for Windows x86
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install -g @quasar/cli yarn --force
          yarn install
      - name: Download VC++ Redistributable x86
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vc14/vc_redist.x86.exe" -OutFile "VC_redist.x86.exe"
          if (!(Test-Path "VC_redist.x86.exe")) { throw "VC_redist.x86.exe download failed" }
      - name: Build and release Windows x86 binaries 
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --bundler builder --publish always -T win32 -A ia32 --icon=/src-electron/icons/icon.ico

